alias up='sudo apt-get update && sudo apt-get dist-upgrade -y'
alias install='sudo apt-get install'
alias carb='ssh carbon -l adrianp'
alias autoremove='sudo apt-get autoremove'
alias install='sudo apt-get install'
alias remove='sudo apt-get remove'
alias serv='sudo service'
alias lxp='ssh lxplus.cern.ch -l apanescu'